FROM	oliverf/builder:buster AS builder

LABEL	maintainer="Oliver Friesen<oliver.friesen@gmail.com>"

ENV	DEBIAN_FRONTEND noninteractive

WORKDIR	/tmp

RUN	apt-get update && \
        apt-get  --quiet --yes --no-install-recommends install \
		libusb-1.0-0-dev \
		libsystemd-dev \
		libev-dev

USER	someuser

RUN	git clone https://github.com/knxd/knxd.git && \
	cd knxd && \
	git checkout v0.14.25  && \
	git format-patch -1 a85099217b0e5fc4408dcc947cded71979fdeec3 && \
        git checkout v0.14.23  && \
	git apply 0001-Use-4.x-branch-of-libfmt-not-master.patch && \
	mv debian/knxd.install.systemd debian/knxd.install.systemd_ && \
	sed '/*/d' debian/knxd.install.systemd_ > debian/knxd.install.systemd && \
	dpkg-buildpackage -b -uc

FROM	debian:stable-slim

RUN	apt-get update && \
	apt-get  --quiet --yes --no-install-recommends install \
		lsb-base \
		libev4 \
		libusb-1.0-0 \
		net-tools && \
	apt-get -q -y clean && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

RUN	adduser --system --disabled-password knxd && \
	usermod -a -G dialout knxd 

COPY	--from=builder /tmp/knxd_*.deb /tmp/
COPY	--from=builder /tmp/knxd-tools_*.deb /tmp/

RUN	dpkg -i /tmp/knxd*.deb

WORKDIR	/home/knxd
COPY	*.ini ./
RUN     chown -R knxd:knxd /home/knxd

USER	knxd
WORKDIR	/home/knxd

ENTRYPOINT ["knxd"]
